spring:
  application:
    name: app

fast2sms:
  api:
    key: 2ZGK1btVqFnIuaj06vcUAYTLdzX8rloRSOw3sEepCgkJ9mPQyMnlOpmx6vihwArNtDuL0s8UBRFzfg4c

server:
  port: ${PORT:8080}

razorpay:
  key-id: rzp_test_SJC89k7q16xRy1
  key-secret: 0QZ83LXMMfTouiFIGEtXhVJE

