spring:
  application:
    name: app
  data:
    mongodb:
      uri: mongodb+srv://yashM05:MLXyash2005@mahalaxmielectricals.mffgdap.mongodb.net/mahalaxmi_rentals?retryWrites=true&w=majority

server:
  port: ${PORT:8080}

razorpay:
  key-id: rzp_test_SJC89k7q16xRy1
  key-secret: 0QZ83LXMMfTouiFIGEtXhVJE
